version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - 8001:8001
    volumes:
      - ${PWD}/src/app/data/test:/nato-object-detector/src/app/data/test
      - ${PWD}/src/app/model/best_model:/nato-object-detector/src/app/model/best_model
    networks:
      - deploy_network
    container_name: military_aircraft_detector_api

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    depends_on:
      - fastapi
    ports:
        - 8501:8501
    volumes:
      - ${PWD}/src/app/data/test:/nato-object-detector/src/app/data/test
      - ${PWD}/src/app/model/best_model:/nato-object-detector/src/app/model/best_model
    networks:
      - deploy_network
    container_name: streamlit

  train_model:
    build:
      context: .
      dockerfile: Dockerfile.trainmodel
    environment:
      FULL_DATASET_DIR: ${FULL_DATASET_DIR}
    volumes:
      - ${FULL_DATASET_DIR}:/nato-object-detector/src/app/data/image_annotations
      - ${PWD}/src/app/model_experiments:/nato-object-detector/src/app/model_experiments
    command: python src/app/train_main.py --full_dataset_dir "/nato-object-detector/src/app/data/image_annotations"
    container_name: train_model

networks:
  deploy_network:
    driver: bridge
