FROM python:3.10-slim

RUN mkdir /nato-object-detector

WORKDIR nato-object-detector

RUN  mkdir -p ./src/app

COPY requirements_fastapi.txt .


RUN pip install -r requirements_fastapi.txt

COPY ./configs/ ./configs
COPY ./src/app/api_models/ ./src/app/api_models
COPY ./src/app/api_routers/ ./src/app/api_routers
COPY ./src/app/model/faster_rcnn.py ./src/app/model/
COPY ./src/app/model/model_utils.py ./src/app/model/
COPY ./src/app/settings/ ./src/app/settings
COPY ./src/app/utils/utils.py ./src/app/utils/
COPY ./src/app/main.py ./src/app/


EXPOSE 8001

ENTRYPOINT ["python"]
CMD ["-m","uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8001"]
