version: '3'

services:
  fastapi:
    image: dmatigol/military_aircraft_detector:faster_rcnn_model
    ports:
      - 8001:8001
    volumes:
      - ${PWD}/src/app/data/test:/nato-object-detector/src/app/data/test
    networks:
      - deploy_network
    container_name: military_aircraft_detector_api

  streamlit:
    image: dmatigol/military_aircraft_detector:streamlit_frontend
    depends_on:
      - fastapi
    ports:
        - 8501:8501
    volumes:
      - ${PWD}/src/app/data/test:/nato-object-detector/src/app/data/test
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge
